# Generated by Django 3.2.3 on 2021-05-18 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_post', models.BooleanField(default=(True, False))),
                ('text', models.CharField(max_length=150)),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('time_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
