# Generated by Django 3.2.3 on 2021-05-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghost_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='type_post',
            field=models.BooleanField(default=False),
        ),
    ]
