# Generated by Django 3.2.3 on 2021-05-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghost_app', '0002_auto_20210519_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='votes',
        ),
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='type_post',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
